disabled_rules:
- identifier_name
- force_cast

excluded:
- CovidStatistics/MockResults.swift
- CSView/MockResults.swift
- CSViewModel/MockResults.swift
- CSModel/MockResults.swift
- CSAPIServer/MockResults.swift
